In [18]:
# 1. Створення одновимірного масиву (вектора) з першими 10-ма натуральними числами
import numpy as np

vector = np.arange(1, 11)
print("Vector:", vector)

Vector: [ 1  2  3  4  5  6  7  8  9 10]


In [19]:
# 2. Створення двовимірного масиву (матриці) розміром 3x3, заповніть його нулями
import numpy as np

matrix_3x3 = np.zeros((3, 3))
print("Matrix 3x3:", matrix_3x3)

Matrix 3x3: [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [20]:
# 3. Створення масиву розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10
import numpy as np

matrix_5x5 = np.random.randint(1, 11, size=(5, 5))
print("Matrix 5x5:", matrix_5x5)

Matrix 5x5: [[ 6 10  5 10  3]
 [ 6  9  3  4  7]
 [ 3  6  1  9  5]
 [ 2  2  7  1 10]
 [ 6  7  3  3  3]]


In [21]:
# 4. Створення масиву розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1
import numpy as np

matrix_4x4 = np.random.rand(4, 4)
print("Matrix 4x4:", matrix_4x4)

Matrix 4x4: [[0.21097491 0.61623639 0.27458348 0.4288348 ]
 [0.81300437 0.25329118 0.63584839 0.56399881]
 [0.09319015 0.8403596  0.13052277 0.48255898]
 [0.43371595 0.49072903 0.31644556 0.46098123]]


In [22]:
# 5. Створення двох одновимірних масивів розміром 5, виконання поелементних операцій
import numpy as np

array1 = np.random.randint(1, 11, size=5)
array2 = np.random.randint(1, 11, size=5)
print("Array1:", array1)
print("Array2:", array2)
print("Addition:", array1 + array2)
print("Subtraction:", array1 - array2)
print("Multiplication:", array1 * array2)

Array1: [ 2  2 10  2  5]
Array2: [ 2  1  6  5 10]
Addition: [ 4  3 16  7 15]
Subtraction: [ 0  1  4 -3 -5]
Multiplication: [ 4  2 60 10 50]


In [23]:
# 6. Створення двох векторів розміром 7, знаходження скалярного добутку
import numpy as np

vector1 = np.random.randint(1, 11, size=7)
vector2 = np.random.randint(1, 11, size=7)
print("Vector1:", vector1)
print("Vector2:", vector2)
print("Dot product:", np.dot(vector1, vector2))

Vector1: [ 7  8  7  5  6  2 10]
Vector2: [ 9  4 10  2  1  5  9]
Dot product: 281


In [24]:
# 7. Створення двох матриць розміром 2x2 та 2x3 та їх перемноження
import numpy as np

matrix1 = np.random.randint(1, 11, size=(2, 2))
matrix2 = np.random.randint(1, 11, size=(2, 3))
print("Matrix 1:\n", matrix1)
print("Matrix 2:\n", matrix2)
try:
    result_matrix = np.dot(matrix1, matrix2)
    print("Result of multiplication:\n", result_matrix)
except ValueError as e:
    print("Error:", e)

Matrix 1:
 [[9 3]
 [1 2]]
Matrix 2:
 [[5 3 6]
 [2 8 6]]
Result of multiplication:
 [[51 51 72]
 [ 9 19 18]]


In [25]:
# 8. Створення матриці розміром 3x3 та знаходження її оберненої матриці
import numpy as np

matrix3 = np.random.randint(1, 11, size=(3, 3))
print("Matrix 3:\n", matrix3)
try:
    inverse_matrix = np.linalg.inv(matrix3)
    print("Inverse of Matrix 3:\n", inverse_matrix)
except np.linalg.LinAlgError as e:
    print("Error:", e)

Matrix 3:
 [[8 1 3]
 [1 4 7]
 [5 6 6]]
Inverse of Matrix 3:
 [[ 0.11464968 -0.07643312  0.03184713]
 [-0.18471338 -0.21019108  0.33757962]
 [ 0.08917197  0.27388535 -0.19745223]]


In [26]:
# 9. Створення матриці розміром 4x4 та транспонування її
import numpy as np

matrix4 = np.random.rand(4, 4)
print("Matrix 4:\n", matrix4)
transposed_matrix = matrix4.T
print("Transposed Matrix 4:\n", transposed_matrix)

Matrix 4:
 [[0.89573209 0.80362831 0.05035642 0.21902158]
 [0.55398178 0.97180527 0.88811306 0.0455751 ]
 [0.18468466 0.55207555 0.57463041 0.97064677]
 [0.60670179 0.23956421 0.72158215 0.99213195]]
Transposed Matrix 4:
 [[0.89573209 0.55398178 0.18468466 0.60670179]
 [0.80362831 0.97180527 0.55207555 0.23956421]
 [0.05035642 0.88811306 0.57463041 0.72158215]
 [0.21902158 0.0455751  0.97064677 0.99213195]]


In [27]:
# 10. Створення матриці розміром 3x4 та вектора розміром 4 та їх перемноження
import numpy as np

matrix5 = np.random.randint(1, 11, size=(3, 4))
vector1 = np.random.randint(1, 11, size=4)
print("Matrix 5:\n", matrix5)
print("Vector 1:\n", vector1)
result_vector = np.dot(matrix5, vector1)
print("Result of matrix-vector multiplication:\n", result_vector)

Matrix 5:
 [[ 7  2  4  7]
 [10  9  7  1]
 [10  8  5  9]]
Vector 1:
 [1 7 6 1]
Result of matrix-vector multiplication:
 [ 52 116 105]


In [28]:
# 11. Створення матриці розміром 2x3 та вектора розміром 3 та їх перемноження
import numpy as np

matrix1 = np.random.rand(2, 3)
vector1 = np.random.rand(3)
print("Matrix 1:\n", matrix1)
print("Vector 1:\n", vector1)
result_vector = np.dot(matrix1, vector1)
print("Result of matrix-vector multiplication:\n", result_vector)

Matrix 1:
 [[0.26075365 0.87725801 0.2931169 ]
 [0.05239736 0.43442807 0.52360782]]
Vector 1:
 [0.41541125 0.27295288 0.58257035]
Result of matrix-vector multiplication:
 [0.51853131 0.44538323]


In [29]:
# 12. Створення двох матриць розміром 2x2 та виконання їхнього поелементного множення
import numpy as np

matrix2 = np.random.randint(1, 11, size=(2, 2))
matrix3 = np.random.randint(1, 11, size=(2, 2))
print("Matrix 2:\n", matrix2)
print("Matrix 3:\n", matrix3)
elementwise_product = np.multiply(matrix2, matrix3)
print("Elementwise product:\n", elementwise_product)

Matrix 2:
 [[5 3]
 [4 6]]
Matrix 3:
 [[5 9]
 [1 1]]
Elementwise product:
 [[25 27]
 [ 4  6]]


In [30]:
# 13. Створення двох матриць розміром 2x2 та знаходження їх добутку
import numpy as np

matrix4 = np.random.randint(1, 11, size=(2, 2))
matrix5 = np.random.randint(1, 11, size=(2, 2))
print("Matrix 4:\n", matrix4)
print("Matrix 5:\n", matrix5)
product_matrix = np.dot(matrix4, matrix5)
print("Product of matrices:\n", product_matrix)

Matrix 4:
 [[2 2]
 [4 3]]
Matrix 5:
 [[2 3]
 [7 2]]
Product of matrices:
 [[18 10]
 [29 18]]


In [31]:
# 14. Створення матриці розміром 5x5 та знаходження суми її елементів
import numpy as np

matrix6 = np.random.randint(1, 101, size=(5, 5))
print("Matrix 6:\n", matrix6)
sum_elements = np.sum(matrix6)
print("Sum of elements:\n", sum_elements)

Matrix 6:
 [[54 17 38 68 47]
 [21  3  3 20 87]
 [ 5 56 66  7 56]
 [ 4 75 63 33 32]
 [83 79 36 76 74]]
Sum of elements:
 1103


In [32]:
# 15. Створення двох матриць розміром 4x4 та знаходження їх різниці
import numpy as np

matrix1 = np.random.randint(1, 11, size=(4, 4))
matrix2 = np.random.randint(1, 11, size=(4, 4))
print("Matrix 1:\n", matrix1)
print("Matrix 2:\n", matrix2)
difference_matrix = np.subtract(matrix1, matrix2)
print("Difference of matrices:\n", difference_matrix)

Matrix 1:
 [[10  2 10  2]
 [ 3  5  5  4]
 [ 3  4  1  5]
 [ 9 10  1  8]]
Matrix 2:
 [[ 6  6  5  1]
 [ 8  4  9  7]
 [10  5  2  9]
 [ 4 10  1  7]]
Difference of matrices:
 [[ 4 -4  5  1]
 [-5  1 -4 -3]
 [-7 -1 -1 -4]
 [ 5  0  0  1]]


In [33]:
# 16. Створення матриці розміром 3x3 та знаходження вектора сум рядків
import numpy as np

matrix3 = np.random.rand(3, 3)
print("Matrix 3:\n", matrix3)
row_sums = matrix3.sum(axis=1)
row_sums_vector = row_sums[:, np.newaxis]
print("Vector of row sums:\n", row_sums_vector)

Matrix 3:
 [[0.66141814 0.32215903 0.96826411]
 [0.24491776 0.21024823 0.43161294]
 [0.48351835 0.25058119 0.76696502]]
Vector of row sums:
 [[1.95184128]
 [0.88677893]
 [1.50106456]]


In [34]:
# 17. Створення матриці розміром 3x4 та матриці з квадратами її елементів
import numpy as np

matrix4 = np.random.randint(1, 11, size=(3, 4))
print("Matrix 4:\n", matrix4)
squared_matrix = np.square(matrix4)
print("Squared matrix:\n", squared_matrix)

Matrix 4:
 [[ 2 10  8  5]
 [ 9  4  7  7]
 [ 3  9  9  9]]
Squared matrix:
 [[  4 100  64  25]
 [ 81  16  49  49]
 [  9  81  81  81]]


In [35]:
# 18. Створення вектора розміром 4 та знаходження вектора з квадратними коренями його елементів
import numpy as np

vector1 = np.random.randint(1, 51, size=4)
print("Vector 1:\n", vector1)
sqrt_vector = np.sqrt(vector1)
print("Vector with square roots:\n", sqrt_vector)

Vector 1:
 [25 40 26  9]
Vector with square roots:
 [5.         6.32455532 5.09901951 3.        ]
